
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkayhzxwkowewgffheer.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrYXloenh3a293ZXdnZmZoZWVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5ODUzMTgsImV4cCI6MjA1ODU2MTMxOH0.HPkaX9TKRAc9P13VnNTduVRtkUNoj0qtfA6oZMjxiss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
